AlquilerAutosProyecto/Controllers/ClientesController.cs
using CapaEntidad;
using CapaNegocio;
using Microsoft.AspNetCore.Mvc;

namespace AlquilerAutosProyecto.Controllers
{
    public class ClientesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        public List<Cliente> listarClientes()
        {
            ClienteBL obj = new ClienteBL();
            return obj.listarClientes();
        } 

        public List<Cliente> filtrarClientes(Cliente objCliente)
        {
            ClienteBL obj = new ClienteBL();
            return obj.filtrarCliente(objCliente);
        }

        public int guardarCliente(Cliente objCliente)
        {
            ClienteBL obj = new ClienteBL();
            return obj.guardarCliente(objCliente);
        }

        public Cliente recuperarDatos(int idCliente)
        {
            ClienteBL obj = new ClienteBL();
            return obj.recuperarDatos(idCliente);
        }

        public bool actualizarCliente(Cliente objCliente)
        {
            ClienteBL obj = new ClienteBL();
            return obj.actualizarCliente(objCliente);
        }

        public bool eliminarCliente(int idCLiente)
        {
            ClienteBL obj = new ClienteBL();
            return obj.eliminarCliente(idCLiente);
        }

        public async Task<Cliente> recuperarEmailContrasenaAsync(string email)
        {
            ClienteBL obj = new ClienteBL();
            return await obj.recuperarEmailContrasenaAsync(email);
        }
    }
}

AlquilerAutosProyecto/Controllers/PagosController.cs
using CapaNegocio;
using CapaDatos;
using Microsoft.AspNetCore.Mvc;
using CapaEntidad;

namespace AlquilerAutosProyecto.Controllers
{
    public class PagosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public List<Pagos> listarPagos()
        {
            PagoBL obj = new PagoBL();
            return obj.listarPagos();
        }

        public List<Pagos> filtrarPagos(Pagos objPago)
        {
            PagoBL lista = new PagoBL();
            return lista.filtrarPagos(objPago);
        }

        public int guardarPagos(Pagos oPagoCLS)
        {
            PagoBL obj = new PagoBL();
            return obj.guardarPago(oPagoCLS);
        }

        public Pagos recuperarPago(int id)
        {
            PagoBL obj = new PagoBL();
            return obj.recuperarPago(id);
        }

        public bool actualizarPago(Pagos objPago)
        {
            PagoBL obj = new PagoBL();
            return obj.actPago(objPago);
        }

        public bool eliminarPago(int objPago)
        {
            PagoBL obj = new PagoBL();
            return obj.eliminarPago(objPago);
        }
    }
}

AlquilerAutosProyecto/Controllers/ReservaController.cs
using CapaNegocio;
using CapaDatos;
using Microsoft.AspNetCore.Mvc;
using CapaEntidad;
using System.Security.Claims;

namespace AlquilerAutosProyecto.Controllers
{
    public class ReservaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult calendario()
        {
            return View();
        }
        public List<Reserva> listarReservas()
        {
            ReservaBL obj = new ReservaBL();
            return obj.listarReservas();
        }

        public List<Reserva> filtrarReserva(Reserva objReserva)
        {
            ReservaBL lista = new ReservaBL();
            return lista.filtrarReserva(objReserva);
        }

        public int guardarReserva(Reserva oReservaCLS)
        {
            ReservaBL obj = new ReservaBL();
            return obj.guardarReserva(oReservaCLS);
        }

        public Reserva recuperarReserva(int id)
        {
            ReservaBL obj = new ReservaBL();
            return obj.recuperarReserva(id);
        }

        public bool actualizarReserva(Reserva objReserva)
        {
            ReservaBL obj = new ReservaBL();
            return obj.actReserva(objReserva);
        }

        public bool eliminarReserva(int objReserva)
        {
            ReservaBL obj = new ReservaBL();
            return obj.eliminarReserva(objReserva);
        }
    }
}

AlquilerAutosProyecto/Controllers/SeguroController.cs
using CapaNegocio;
using CapaDatos;
using Microsoft.AspNetCore.Mvc;
using CapaEntidad;

namespace AlquilerAutosProyecto.Controllers
{
    public class SeguroController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public List<Seguro> listarSeguros()
        {
            SeguroBL obj = new SeguroBL();
            return obj.listarSeguro();
        }

        public List<Seguro> filtrarSeguros(Seguro objSeguro)
        {
            SeguroBL obj = new SeguroBL();
            return obj.filtrarSeguro(objSeguro);
        }

        public int guardarSeguro(Seguro objSeguro)
        {
            SeguroBL obj = new SeguroBL();
            return obj.guardarSeguro(objSeguro);
        }

        public Seguro recuperarDatos(int idSeguro)
        {
            SeguroBL obj = new SeguroBL();
            return obj.recuperarDatos(idSeguro);
        }

        public bool actualizarSeguro(Seguro objSeguro)
        {
            SeguroBL obj = new SeguroBL();
            return obj.actualizarSeguro(objSeguro);
        }

        public bool eliminarSeguro(int idSeguro)
        {
            SeguroBL obj = new SeguroBL();
            return obj.eliminarSeguro(idSeguro);
        }
    }
}

AlquilerAutosProyecto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlquilerAutosProyecto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha512-oe8OpYjBaDWPt2VmSFR+qYOdnTjeV9QPLJUeqZyprDEQvQLJ9C5PCFclxwNuvb/GQgQngdCXzKSFltuHD3eCxA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    <script src="https://cdn.datatables.net/2.2.2/js/dataTables.js"></script>
    <link rel="stylesheet" href="~/AlquilerAutosProyecto.styles.css" asp-append-version="true" />


</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AUTOSIGLO</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">

                <label class="switch">
                    <div class="round">
                        <input name="onoff" id="onoff" type="checkbox" class="input-nav">
                        <div class="back"><label for="onoff" class="but"><span class="on">0</span><span class="off">I</span></label></div>
                    </div>
                </label>

                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <!-- Si el usuario está autenticado, muestra el botón de Cerrar Sesión -->
                    <li class="nav-item">
                        <span class="nav-link text-white">Bienvenido, @User.Identity.Name</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Login" asp-action="Logout">Cerrar sesión</a>
                    </li>
                }
                else
                {
                    <!-- Si el usuario no está autenticado, muestra el botón de Iniciar Sesión -->
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Login" asp-action="Index">Iniciar sesión</a>
                    </li>
                }

            </ul>
        </div>
    </nav>

    <input type="hidden" id="hdfOculto" value="@Url.Content("~")" />
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted"> *@
    @*     <div class="container"> *@
    @*         &copy; 2025 - AlquilerAutosProyecto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
    @*     </div> *@
    @* </footer> *@
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.css" />

    <script src="https://cdn.datatables.net/2.2.2/js/dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AlquilerAutosProyecto/Views/Shared/_LayoutAdmin.cshtml
@{
    ViewData["Title"] = "_LayoutAdmin";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlquilerAutosProyecto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha512-oe8OpYjBaDWPt2VmSFR+qYOdnTjeV9QPLJUeqZyprDEQvQLJ9C5PCFclxwNuvb/GQgQngdCXzKSFltuHD3eCxA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    <script src="https://cdn.datatables.net/2.2.2/js/dataTables.js"></script>
    <link rel="stylesheet" href="~/AlquilerAutosProyecto.styles.css" asp-append-version="true" />

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AUTOSIGLO</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">

                <label class="switch">
                    <div class="round">
                        <input name="onoff" id="onoff" type="checkbox" class="input-nav">
                        <div class="back"><label for="onoff" class="but"><span class="on">0</span><span class="off">I</span></label></div>
                    </div>
                </label>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Pagos" asp-action="Index">Pagos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Reserva" asp-action="Index">Reservas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Empleado" asp-action="Index">Empleados</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Vehiculos" asp-action="Index">Vehiculos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Seguro" asp-action="Index">Seguro</a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <!-- Si el usuario está autenticado, muestra el botón de Cerrar Sesión -->
                    <li class="nav-item">
                        <span class="nav-link text-white">Bienvenido, @User.Identity.Name</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Login" asp-action="Logout">Cerrar sesión</a>
                    </li>
                }
                else
                {
                    <!-- Si el usuario no está autenticado, muestra el botón de Iniciar Sesión -->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Login" asp-action="Index">Iniciar sesión</a>
                    </li>
                }

            </ul>
        </div>
    </nav>


    <input type="hidden" id="hdfOculto" value="@Url.Content("~")" />
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted"> *@
    @*     <div class="container"> *@
    @*         &copy; 2025 - AlquilerAutosProyecto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
    @*     </div> *@
    @* </footer> *@
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.css" />

    <script src="https://cdn.datatables.net/2.2.2/js/dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>